apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: onboarding-ms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding-ms
  template: 
    metadata:
      labels:
        app: onboarding-ms
    spec:
      containers:
        - name: onboarding-ms
          image: 89910907/onboarding-ms
          env:
            - name: BROKER
              value: kafka-service:9092

---

apiVersion: v1
kind: Service 

metadata:
  name: onboarding-ms-svc
spec:
  selector:
    app: onboarding-ms
  ports:
    - name: onboarding-ms
      protocol: TCP
      port: 3000
      targetPort: 3000